title: "Neotoma age-depth"
author:
  - name: "Quinn Asena"
    affiliation: "Cary Institute for ecosystem Sciences"
  - name: "Jack Williams"
    affiliation: "University of Wisconsin-Madison"
  - name: "Simon Goring"
    affiliation: "University of Wisconsin-Madison"    
date: today
format:
  html:
    code-fold: false
    toc: true
    link-external-newwindow: true
    
bibliography: refs.bib
from: markdown+emoji
embed-resources: true

execute: 
  cache: true
theme:
  light: flatly
  dark: darkly